export enum Authority {
  ADMIN = 'ROLE_ADMIN',
  USER = 'ROLE_USER',
  AUDITOR = 'ROLE_AUDITOR',
  MANAGER = 'ROLE_MANAGER',
  VICE_PRESIDENT = 'ROLE_VICE_PRESIDENT',
  PRESIDENT = 'ROLE_PRESIDENT',
}
